### ISSUE TITLE
Some questions about Selscan

### ISSUE THREAD

**Issue by Yun-HongWu** [szpiech/selscan#34]
Dear  Szpiech,

Recently, i am doing a genome-wide scans of posotive selections on my data sets with your software "Selscan". In my analysis, i have used the --nSL to identifying the candidate selected regions (the input file is phased VCF files), and following your manuals i have got the output files (selscan+norm pipeline). But now there are some questions confused me and need your help. 
First, when i use command "norm --nsl --files <file1.*.out> ... <fileN.*.out>" to normalize selscan output across frequency bins, the output files generated by norm have no header information about each column. Such as 
.       180387  0.0571429       100.917 25.766  1.36524 1.54632 0
.       181142  0.385714        28.9231 49.4042 -0.535396       -0.191878       0
.       182751  0.228571        55.5    33.1852 0.514279        1.15106 0
.       183083  0.385714        29.5385 49.5183 -0.516649       -0.16627        0
.       184456  0.371429        30.8031 47.1786 -0.426327       -0.048742       0

and what is the mean for the last column (such as the value "0").
Second, if i use the command "norm --nsl --files <file1.*.out>...<fileN.*.out> --bp-win --winsize 20000" to normalize my selscan results, the formats of the normalized files are like this:
1       20001   0       -1      -1
20001   40001   0       -1      -1
40001   60001   0       -1      -1
60001   80001   0       -1      -1
80001   100001  0       -1      -1
100001  120001  0       -1      -1
120001  140001  0       -1      -1
140001  160001  0       -1      -1
160001  180001  0       -1      -1
180001  200001  19      0       100
200001  220001  8       0       -1
220001  240001  89      0       100
240001  260001  22      0.0454545       100
260001  280001  30      0       100

for the first two columns, i know they are the positions of each window, but i have no idea about the rest three columns, what do they mean? 

The last question is how do i identify the candidate regions of positive selections based on the output files of Selscan? For example, if i use the normalized output file generated by  norm (without --bp-win parameter), should i just pick out the loci as the candidates of postive selections ,for which their normalized values fall in  the extreme 1%  or 99% ranges? And if i use the normalized results generated by norm with --bp-win and --winsize, what is the best way to pick out the candidate loci/regions from the genome-wide windowed values?

Looking forward your replies !
Thank you in advance

**Comment by szpiech** [comment]
For the output you give first the format is ```<snp id> <position> <allele frequency of '1' allele> <SL1> <SL0> <raw nSL> <normalized nSL> <is nSL greater than critical value? 1 yes; 0 no>```

For the second output, the format is ```<start window> <end window> <nScores in window> <fraction grater than critical value> <percentile relative to other winows in nScores bin>```

You would typically take the windows in the top 0.1 or 1 percent as putative regions under ongoing positive selection.

Hope this helps.

**Comment by ChrisK1988** [comment]
Hi @szpiech,

Instead of starting a new comment on this I figured I would piggyback on this one as I also have questions regarding the output in the *.windows and *.norm files. Briefly, I used selscan/2.0.3 with the --nsl flag to obtain a series of scores per chromosome for 12 modern human populations that have regions of interest to me. I normalized these values as per your general parameters in your 2021 macaque paper (https://academic.oup.com/evlett/article/5/4/408/6697682#401494707). 

while read i; do norm --nsl --files Outputs/${i}.chr*.nsl.out --bp-win --winsize 100000 --qbins 10 --min-snps 10; done < Pops.txt

The output is as follows:

1       100001  0       -1      -1      NA
100001  200001  0       -1      -1      NA
200001  300001  253     0.0118577       100     2
300001  400001  273     0.0659341       100     2
400001  500001  149     0.154362        100     2
500001  600001  210     0.119048        100     2
600001  700001  208     0       100     1
700001  800001  161     0.0248447       100     3
800001  900001  191     0.026178        100     2
900001  1000001 227     0.00440529      100     2
[ ... ]
2000001 2100001 329     0.164134        5       3
2100001 2200001 677     0.00443131      100     2
2200001 2300001 61      0.0655738       100     2
2300001 2400001 120     0       100     1
2400001 2500001 106     0.122642        100     2

Based on your above comment this would suggest that there are only 5 columns for the *.windows file, however, I have 6. Is column 6 the critical value of the window? If so, how do I interpret this? Is it enough to say this region is under putative selection when the fraction greater than the critical value (column 4) reaches a threshold, which would be either greater than 5% or 1% of the windowed values in the same file (i.e. column 5 presenting this value)? If this is the case, I am just a bit confused because window 2400001-2500001 has a 12% fraction greater than the critical value, but is apparently at the bottom 100% of the distribution, but another window (2000001-2100001) has a 16.4% fraction that is at the top 5% of the distribution. It doesn't make sense because other windows have much smaller fractions (say 0.02%) but are also lumped into the bottom 100%. Is this interpretation correct? How would we interpret these results in a genome-wide context, or they alternatively, better interpreted in isolation per chromosome?

Additionally, my *.norm files have the expected columns. Would it be enough here to take SNPs denoted with 1 in the final column as "interesting" enough to qualify for selection? Or is it better to pool these together genome-wide and just take the top 1% of the 7th column as is typically done for a number of these outlier-style approaches?

.       245254  0.147059        84.0057 35.936  0.368779        0.165865        0
.       246274  0.308824        42.1979 50.659  -0.0793658      -1.24225        0
.       246665  0.0784314       130.068 32.8323 0.597868        0.957187        0
.       246884  0.534314        26.2603 93.5685 -0.55183        -2.25784        1
.       247042  0.431373        35.0737 66.1292 -0.275412       -1.53775        0

Sorry for the extensive comment. I appreciate any and all help.

-Chris

**Comment by ChrisK1988** [comment]
Hi Zachary,

Thank you, that did help. Just to make sure I am interpreting everything correctly, would you be able to confirm my thinking? I added a header to keep things straightforward. In this particular segment on chr5, all windows are at the bottom of the distribution since they have a relative percentile of 100, correct? Therefore, I would be looking for windows that are labelled as 1 in that column if I wanted to see windows at the top 1% of the genome-wide distribution? Or are these values only normalized to the chromosome they are in? If the latter is true, how would you convert this output to look at genome-wide values (I have concatenated all of the chromosomes together already and ran norm as above)? The output is as follows:

chr    win_start  win_end    nScores_in_window  fraction>_critval  relative_percentile_placement_of_win  maxval_in_window_truncated
chr5   152200001  152300001  200                0.02               100                                   2
chr5   152300001  152400001  320                0                  100                                   1
chr5   152400001  152500001  367                0                  100                                   1
chr5   152500001  152600001  217                0.0184332          100                                   2
chr5   152600001  152700001  200                0.055              100                                   2
chr5   152700001  152800001  139                0.00719424         100                                   2
chr5   152800001  152900001  188                0.00531915         100                                   2
chr5   152900001  153000001  158                0                  100                                   1
chr5   153000001  153100001  164                0                  100                                   1

I also wanted to ask too, since I am also using XP-nSL, if I wanted to identify genome-wide outliers for the norm'd XP-nSL output, would the interpretation be the same, but this time for columns 7 (approx % for gt threshold windows) and 8 (approx % for lt threshold windows), as outlined here? https://github.com/szpiech/selscan/issues/78 As in if the window is labelled as 1 for column 7 it would be that window is at the top 1% for all other windows across the genome for PopA and if it has a 1 for column 8 that would be at the top 1% for all other windows across the genome for PopB? Or is it better to simply take the top 1% for column 9 (max_score) and the bottom 1% for column 10 (min_score) in order to get the genome-wide outlier approach after combining all chromosomes?

chr    win_start  win_end    #_scores_in_window  frac_scores>thresh  frac_scores<thresh  approx%_for>threshold_windows  approx%_for<threshold_windows  max_score     min_score
chr1   700001     800001     336                 0.0357143           0                   100
100                            2.31097       -1.30734
chr1   800001     900001     947                 0.00211193          0                   100
100                            2.03811       -1.24538
chr1   900001     1000001    1241                0.0402901           0                   100
100                            2.71529       -1.95747
chr1   1000001    1100001    1019                0.31894             0                   5
100                            3.26658       -0.827097
chr1   1100001    1200001    1211                0.1346              0                   100
100                            2.86858       -1.15271
chr1   1200001    1300001    1181                0                   0                   100
100                            1.9332        -1.84536
chr1   1300001    1400001    921                 0.100977            0                   100


Thank you very much, I hope after this that will be the end of my questions for you. You have been very helpful.

Chris

**Comment by szpiech** [comment]
Hi Chris,

Yes, you are correct for the top file with nsl norm.windows output. The
normalization and percentiles are computed with respect to all the data you
give norm. So if you gave it all chromosomes it is computed with respect to
all chromosomes.

For the xpnsl file, your labels look correct. As for which approach you
want to take, it depends on your goals. In the Szpiech et al 2021 Evo Lett
paper I explore how taking the max value vs enriched window influences
power to find regions under selection, concluding that looking for enriched
windows performs a bit better. Again, there may be other reasons why one
may prefer max/raw scores.

Zachary

**Comment by ChrisK1988** [comment]
Thanks, @szpiech, really appreciate all of your comments (and how quick they come too!). This helped immensely.
