### ISSUE TITLE
Working with the iHH12 statistic

### ISSUE THREAD

**Issue by RamGonzalez** [szpiech/selscan#79]
Hi professor Szpiech,

I have some questions regarding the output of the iHH12 statistic:

1. After normalization, what does a negative score imply? If I remember correctly, for iHS meant selection on either the derived or ancestral haplotype. Is this the case with iHH12?

2. Should I then report the absolute value of iHH12, like in iHS and nSL?

3. Is prior filtering of only SNPs with ancestral/derived states needed for iHH12?

I'd appreciate your input on this. Best,
Ram

**Comment by szpiech** [comment]
Hi Ram,

To answer your questions,

1. iHH12 is calculating integrated haplotype homozygosity (with top two hap classes collapsed) of the whole sample (not the ratio of the iHH or anc/der as in iHS), therefore normalized scores that are negative are just reflecting their very low iHH12 score (lots of heterozygosity among haplotypes). 
2. No, positive scores are the important ones.
3. I haven't investigated this in depth, since we aren't splitting and comparing iHH among anc/der haplotypes, I suspect it makes little if any difference.
Hope this helps!

**Comment by RamGonzalez** [comment]
Hi professor Szpiech,
Thank you for your response, the use and interpretation of this statistic is much more clear to me now! :-)

Best,
Ram
